SHARE-324 Report Rework
HCrane/CAPI pull request #27
Opened 2020-07-18 14:00 UTC by wolfianer

Added report project to new api.

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) of this repository.

- [x] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no warnings and errors 
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Verify that all tests are passing, if not please state the test cases in the [section](#Tests) below
- [x] Perform a self-review of the changes
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch

2020-07-20 07:41 UTC, dmetzner requested changes

2020-07-20 07:41 UTC, dmetzner commented on catroweb.yaml
> +    ProjectReportResponse:
typo: should be a Request object

2020-07-20 07:41 UTC, dmetzner commented on catroweb.yaml
> +        project_id:
Here the project id is already part of the path: `projects/{ID}/report`

No need for it to be sent a second time in the body

2020-07-20 07:41 UTC, dmetzner commented on catroweb.yaml
> +        user_id:
why do we need a user id in this request?

project owner is available through the project

and the reporter (a user) is available through the JWT token. User must be authorized to report

2020-07-20 07:41 UTC, dmetzner commented on catroweb.yaml
> +          $ref: '#/components/responses/BadRequest'
Add  response code for missing/failed authentification

```
401 | Invalid JWT token \| JWT token not found \| JWT token expired
```

2020-07-21 17:38 UTC, HCrane requested changes

2020-07-21 17:38 UTC, HCrane commented on catroweb.yaml
> +          example: Graphic violence
This should be an enum with the categories provided by the report dialogue.

2020-08-20 07:24 UTC, HCrane approved these changes
👍

2020-08-20 07:24 UTC, dmetzner approved these changes

2020-08-20 07:25 UTC, merged