SHARE-378-Notifications-Capi
HCrane/CAPI pull request #35
Opened 2020-08-16 08:44 UTC by arminpasalic10

- Added the neccessary documentation for the api routes of notifications

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) of this repository.

- [x] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no warnings and errors 
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Verify that all tests are passing, if not please state the test cases in the [section](#Tests) below
- [x] Perform a self-review of the changes
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [x] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### Additional Description
`TODO: Add additional information that is not in your commit-message here`

### Tests - additional information
`TODO: add additional information about testruns here`

2020-08-16 09:56 UTC, dmetzner requested changes
details in discord

2020-08-20 08:41 UTC, HCrane requested changes

2020-08-20 08:41 UTC, HCrane commented on catroweb.yaml
> +      example: reaction
Please be careful with naming conventions (i know it is in another section but still.).

Also type should be an enum which should default to `all`.

2020-08-20 08:41 UTC, HCrane commented on catroweb.yaml
> +  '/notifications/markasread/{id}':
Route should be `/notification/{id}/read` --> makes a bit more sense.

2020-08-20 08:41 UTC, HCrane commented on catroweb.yaml
> +  /notifications/markall:
Route should be `/notifications/read`.

2020-08-20 08:41 UTC, HCrane commented on catroweb.yaml
> +          example: 3
Please change `all` to `total`. Likes etc should be singular eg `likes` should be `like` .

2020-08-20 08:41 UTC, HCrane commented on catroweb.yaml
> +    NotificationFetchResponse:
Small change please remove the word `Fetch`.

2020-08-20 08:41 UTC, HCrane commented on catroweb.yaml
> +          description: Id of the user who caused the notification
Please use the `schema.Uuid`.

2020-08-20 08:41 UTC, HCrane commented on catroweb.yaml
> +          description: Id of the program for which the notification is about
Please use the `schema.Uuid`.

2020-08-20 08:41 UTC, HCrane commented on catroweb.yaml
> +          description: Id of the remixed program for remix notifications
Please use the `schema.Uuid`.

2020-08-21 06:47 UTC, dmetzner requested changes

2020-08-21 06:47 UTC, dmetzner commented on catroweb.yaml
> +        program:
Even with UUIDs a unique description would be nice to describe the field to other teams.
![image](https://user-images.githubusercontent.com/40868718/90860533-779d2200-e38a-11ea-9e6d-f5c9eaba4e5e.png)

2020-08-21 06:47 UTC, dmetzner commented on catroweb.yaml
> +        - all
also, use total here

2020-08-21 06:47 UTC, dmetzner commented on catroweb.yaml
> +        program:
A possible workaround is to wrap $ref into allOf - this can be used to "add" attributes to a $ref but not override existing attributes.

2020-08-21 09:14 UTC, arminpasalic10 commented on catroweb.yaml
> +        - all
"All" makes much more sense than "total" in this context since this is indicating the type of container/section that the notifications should be fetched for. And currently, the name of the section is "All" notifications and not "total" notifications

2020-08-24 16:08 UTC, dmetzner approved these changes

2020-08-24 17:31 UTC, HCrane approved these changes

2020-08-24 17:32 UTC, merged